sudo: false

language: node_js

notifications:
  email: false

node_js:
- stable

cache:
  directories:
  - node_modules

before_script:
- npm prune

script:
- npm run test

after_success:
- npm run release

branches:
  only:
  - master
